version: '3.5'

services:
  griddb:
    #image: griddbnet/griddb
    build:
      context: ./griddb
      dockerfile: Dockerfile
    ports:
      - "10001:10001"
      - "10010:10010"
      - "10020:10020"
      - "10030:10030"
      - "10040:10040"
      - "10050:10050"
      - "10080:10080"
      - "20001:20001"

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8888:8888"

  initializer:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["./run_init.sh"]
